[project]
name = "my-project"
version = "0.1.0"
requires-python = ">=3.11,<3.13"
dependencies = [
    "pandas==2.1.4",
    "numpy>=1.23.0",
]

[build-system]
requires = ["setuptools>=61.0", "wheel", "Cython>=0.29.36,<3.0"]
build-backend = "setuptools.build_meta"