services:
  - type: web
    name: my-app
    env: python
    pythonVersion: "3.11"  # Add or update this line
    buildCommand: pip install .  # Or "pip install -r requirements.txt" if using requirements.txt
    startCommand: gunicorn app:app